config/routes.rb
Rails.application.routes.draw do
 

  namespace :account do
    resources :posts
  end

  devise_for :users

  resources :groups do
    resources :posts
  end

  get 'welcome/index' => "welcome#index"
  get "reviews" => "groups#index"

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
  has_many :posts
	validates :title, presence: true
  mount_uploader :image, ImageUploader

	scope :recent, -> {order("created_at DESC")}

	def self.search(search)
  		if search
    		#where("title LIKE ?", "%#{search}%") 
  			where("title LIKE :search OR description LIKE :search", search: "%#{search}%")
  		else
    		all
    	end
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	validates :content, presence: true

	belongs_to :user
  	belongs_to :group
  	
  	scope :recent, -> {order("created_at DESC")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

	before_action :authenticate_user!
	
  def index
    @posts = current_user.posts.recent.paginate(:page => params[:page], :per_page => 10)
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	
	before_action :authenticate_user! , only: [:edit, :update, :new, :destroy]

	def index
    if params[:search]
      @groups = Group.search(params[:search]).recent.paginate(:page => params[:page], :per_page => 5)
    else 
    	@groups = Group.all.recent.paginate(:page => params[:page], :per_page => 5)
    end
	end

	def new
		@group = Group.new
	end	
	def create
   		@group = Group.new(group_params)
   		if @group.save
   			redirect_to groups_path
   		else
      		render :new
      	end
 	end
 	def show
 		@group = Group.find(params[:id])
 		@posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 10)
 	end
 	def edit
 		@group = Group.find(params[:id])
 	end
 	def update
    	@group = Group.find(params[:id])

    	@group.update(group_params)

    	redirect_to groups_path
  	end
  	def destroy
    	@group = Group.find(params[:id])
    	@group.destroy

    	redirect_to groups_path
	end

 	private

 	def group_params
   		params.require(:group).permit(:title, :description, :image)
 	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_filter :authenticate_user!, :only => [:new, :create]

  	
  	def new
    	@group = Group.find(params[:group_id])
    	@post = Post.new
  	end
  	def create
   		@group = Group.find(params[:group_id])
    	@post = Post.new(post_params)
    	@post.group = @group
    	@post.user = current_user
    	if @post.save
      		redirect_to group_path(@group)
    	else
      		render :new
    	end
  	end
  	def edit
  		@group = Group.find(params[:group_id]) 
  		@post = Post.find(params[:id])
  	end
  	def update
    	@group = Group.find(params[:group_id])
    	@post = Post.find(params[:id])

    	if @post.update(post_params)
    		redirect_to account_posts_path
    	else
    		render :edit
    	end
  	end
  	def destroy
    	@group = Group.find(params[:group_id])
    	@post = Post.find(params[:id])
    	@post.destroy

    	redirect_to account_posts_path
	end

  	private

  	def post_params
    	params.require(:post).permit(:content)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index  	
  	@groups = Group.all.limit(5).recent
  end
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="/">Online Book Reviews</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    
                    <li>
                        <a href=welcome/index#latest>What's news</a>
                    </li>
                    <li>
                        <%= link_to 'Reviews', reviews_path %>
                    </li>
                        <% if !current_user %>
                        <li><%= link_to("Register", new_user_registration_path) %> </li>
                        <li><%= link_to("Login", new_user_session_path) %></li>
                        <% else %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!, <%= current_user.email %>
                            <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li> <%= link_to("My Reviews", account_posts_path) %></li> 
                                <li class="divider"> </li>
                                <li> <%= link_to("Log out", destroy_user_session_path, method: :delete) %> </li>
                            </ul>
                  </li>
                <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>

<div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control", :rows => 4} %>
    <%= f.file_field :image %>
</div>
<div class="row">
<div class="col-md-3">
<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting" } %>
</div>
<div class="col-md-4">
<%= link_to("Cancel", groups_path, class: "btn btn-md btn-default")%>
</div>
</div>
<% end %>


<!--something that do not need, but keep for ref
< % if @group.errors.any? %>
<ul>
  < % @group.errors.full_messages.each do |msg| %>
    <li>< %= msg %></li>
  < % end %>
</ul>
< % end %>
-->    

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4" id="article">
    <h2>Edit the book information</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="banner">
    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <h2>Enrich Your Life With Books:</h2>
            </div>
            <div class="col-lg-6">
                <ul class="list-inline">
                    <div class="group">
                      <%= link_to("Add New Book", new_group_path, class: "btn btn-lg btn-default pull-right") %>
                    </div>                       
                </ul>
                </div>
        </div>
    </div>
    <!-- /.container -->
  </div>
<!-- /.banner -->
  
<div class="col-md-12" id="review_body">
  <%= form_tag groups_path, id: "search-form", :method => "get" do %>  
  <%= submit_tag "Search", class: 'btn btn-default pull-right', name: nil %>
  <%= text_field_tag :search, params[:search], class: 'btn btn-default pull-right', placeholder: "Search Books" %>    
  <% end %>
</div>

<!--review body-->
<div class="col-md-12" id="review_body">
  
  <!-- <table class="table table-hover">
    <thead>
      <tr>
        <td></td>
        <td><h4>Title</h4></td>
        <td><h4>Description</h4></td>
      </tr>
    </thead>
    <tbody>
      < % @groups.each do |group| %>
        <tr>
          <td></td>
          <td>< %= link_to(group.title, group_path(group)) %></td>
          <td>< %= simple_format(group.description) %></td>
          <td>
              < % if current_user %>
                < %= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
                < %= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
              < % end %>
          </td>
        </tr>
      < % end %>
    </tbody>
  </table> -->

  <% @groups.each do |group| %>
      <div class="row container">
            <div class="col-md-5">
                <div class="img-fluid rounded mb-3 mb-md-0">                    
                    <%= image_tag group.image.thumb %>
                </div>
            </div>
            <div class="col-md-7">
                <h3 class="text-primary"><%= group.title %></h3>
                <hr>
                <p><%= simple_format(group.description) %></p>
                <% if current_user %>
                <%= link_to("Edit", edit_group_path(group), class: "btn btn-md btn-default")%>
                <%= link_to("Delete", group_path(group),    class: "btn btn-md btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
                <% end %>
                <%= link_to("See More Reviews >>", group_path(group),class: "btn btn-md btn-primary") %>
            </div>
      </div>
      <hr>
  <% end %>

  <div class="text-center">
    <%= will_paginate @groups %>
  </div>

</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4" id="article">
    <h2>Add new book to write review!</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12" id="content">

  <h2><%= @group.title %></h2>
  <p><%= simple_format(@group.description) %></p>

  <div class="group row">
    	<%= link_to("Edit Book Info", edit_group_path(@group), class: "btn btn-primary btn-md")%>   
    	<%= link_to("Write Review", new_group_post_path(@group), class: "btn btn-primary btn-md")%>   
    	<%= link_to("Go Back to List", groups_path, class: "btn btn-primary btn-md")%>    
  </div>
	<br>
	<table class="table">
    <thead>
      <tr>
        <th>Reviews</th>
        <th>Author</th>
        <th>date</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= simple_format(post.content) %></td>
          <td><%= post.user.email %></td>
          <td><%= post.created_at.to_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
  	<%= will_paginate @posts %>
  </div>

</div>


	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/landing-page.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <title>Book Reviews</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>

	<div>
        <%= render "common/navbar" %>
        <%= yield %>
    </div>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/posts/_form.html.erb
<%= simple_form_for [@group, @post] do |f| %>

<div class="form-group">   
    <%= f.input :content, input_html: { class: "form-control", :rows => 4} %>
</div>
<div class="row">
<div class="col-md-3">
<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting" } %>
</div>
<div class="col-md-4">
<%= link_to("Cancel", account_posts_path, class: "btn btn-md btn-default")%>
</div>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-4 col-md-offset-4" id="article">
    <h2>Edit your Reviews!</h2>
    <hr>
    <%= render "form" %>
    
</div>

app/views/posts/new.html.erb
<div id="rev_con">

<h2 class="text-center">Write some Review!</h2><br>

<div class="col-md-4 col-md-offset-4">

  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: {class: "form-control", :rows =>10}%>
    </div>
	<div class="row">
		<div class="col-md-3">
			<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting" } %>
		</div>
		<div class="col-md-4">
			<%= link_to("Cancel", group_path(@group), class: "btn btn-md btn-default")%>
		</div>
  	<% end %>
</div>

</div>

app/views/welcome/index.html.erb
    <!-- Header -->
    <a name="Sign-in"></a>
    <div class="intro-header">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Book Reviews</h1>
                        <h3>Let's find some awesome books!</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline">

                            <li>
                                <div class="btn-block">
                                <%= form_tag groups_path, id: "search-form", :method => "get" do %>  
                                <%= text_field_tag :search, params[:search], class: 'btn btn-default btn-lg', placeholder: "Search Books" %>
                                <%= submit_tag "Search", class: 'btn btn-default btn-lg', name: nil %>        
                                <% end %> 
                                </div>
                            </li>   
                                                       
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
    <!-- Page Content -->
    <a name="latest"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Collection for you:<br>Latest Updated Book!</h2>
                    <table class="table table-hover"> 
                        <% @groups.each do |group|  %>
                            <tr>
                              <td class="text-success lead">
                                <%= group.title %> &emsp; ( <%= group.updated_at.to_date %> )  
                              </td>
                            </tr>
                        <% end %>
                    </table>         
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive img-thumbnail" src="/assets/read.jpg" alt="">
                </div>
            </div>

        </div>
    </div>
    
    
    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Write down <br>what you're thinking:</h2>
                    <ul class="list-inline">
                        <li>
                        <%= link_to('See Reviews', reviews_path, class: "btn btn-default btn-lg")%>
                        </li>
                        <li>
                        <%= link_to("Add Book", new_group_path, class: "btn btn-default btn-lg")%>
                        </li> 
                    </ul>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/assets/dog.png" alt="">
                </div>
            </div>

        </div>
    </div>
    



    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href=#latest>What's news</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <%= link_to 'Reviews', reviews_path %>
                        </li>

                        <% if !current_user %>
                        <li class="footer-menu-divider">&sdot;</li>                       
                        <li>
                            <%= link_to("Login", new_user_session_path) %>
                        </li>
                        <% end %>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Online Book Reviews 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>